In [3]:
import geopandas as gpd

In [ ]:
import os
data_folder_path = 'C:\Users\lucaf\Desktop\Earth Observation\Data'
filename = 'karnataka.gpkg'
path = os.path.join(data_folder_path, filename)

In [5]:
roads_gdf = gpd.read_file(path, layer='karnataka_major_roads')
roads_gdf

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry
0,4354953,5114,secondary,Mahatma Gandhi Road,NaN,F,30,0,F,F,"MULTILINESTRING ((77.59928 12.97672, 77.5995 1..."
1,8285861,5114,secondary,NaN,NaN,B,0,0,F,F,"MULTILINESTRING ((76.65944 12.31809, 76.65904 ..."
2,8285868,5113,primary,Bangalore Nilgiri Road,NaN,F,0,0,F,F,"MULTILINESTRING ((76.65906 12.31389, 76.65912 ..."
3,8285890,5115,tertiary,Sri Harsha Road,NaN,F,0,0,F,F,"MULTILINESTRING ((76.656 12.30895, 76.65646 12..."
4,8285892,5114,secondary,Ashoka Road,NaN,F,0,0,F,F,"MULTILINESTRING ((76.65615 12.30989, 76.656 12..."
...,...,...,...,...,...,...,...,...,...,...,...
44601,763293423,5114,secondary,Kamaraj Road,NaN,F,0,0,F,F,"MULTILINESTRING ((77.60806 12.97517, 77.60797 ..."
44602,763293424,5114,secondary,Mahatma Gandhi Road,NaN,F,30,0,F,F,"MULTILINESTRING ((77.60798 12.97519, 77.60806 ..."
44603,763295978,5114,secondary,18th Cross Road,NaN,B,0,0,F,F,"MULTILINESTRING ((77.57115 13.00849, 77.57156 ..."
44604,763405052,5113,primary,Varthur Road,NaN,F,0,0,F,F,"MULTILINESTRING ((77.7014 12.95693, 77.70164 1..."
44605,763405053,5113,primary,Field Marshal Cariappa Road,NaN,F,30,0,F,F,"MULTILINESTRING ((77.6104 12.9736, 77.61052 12..."

In [6]:
roads_gdf.geometry

0        MULTILINESTRING ((77.59928 12.97672, 77.5995 1...
1        MULTILINESTRING ((76.65944 12.31809, 76.65904 ...
2        MULTILINESTRING ((76.65906 12.31389, 76.65912 ...
3        MULTILINESTRING ((76.656 12.30895, 76.65646 12...
4        MULTILINESTRING ((76.65615 12.30989, 76.656 12...
                               ...
44601    MULTILINESTRING ((77.60806 12.97517, 77.60797 ...
44602    MULTILINESTRING ((77.60798 12.97519, 77.60806 ...
44603    MULTILINESTRING ((77.57115 13.00849, 77.57156 ...
44604    MULTILINESTRING ((77.7014 12.95693, 77.70164 1...
44605    MULTILINESTRING ((77.6104 12.9736, 77.61052 12...
Name: geometry, Length: 44606, dtype: geometry

In [7]:
filtered = roads_gdf[roads_gdf['ref'].str.match('^NH') == True]
filtered

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry
17,8684837,5112,trunk,Bengaluru - Mangaluru Road,NH373,F,0,0,F,F,"MULTILINESTRING ((76.10024 13.00326, 76.0995 1..."
26,9951034,5112,trunk,NaN,NH948,B,50,0,F,F,"MULTILINESTRING ((77.16472 12.24774, 77.16416 ..."
54,22838314,5112,trunk,Solapur-Mangalore Highway,NH169,B,0,0,F,F,"MULTILINESTRING ((74.86387 12.88387, 74.86418 ..."
55,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,"MULTILINESTRING ((74.78756 13.09142, 74.78744 ..."
56,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,"MULTILINESTRING ((74.78767 13.09723, 74.78767 ..."
...,...,...,...,...,...,...,...,...,...,...,...
44466,760685447,5112,trunk,Outer Ring Road,NH75,F,60,0,F,F,"MULTILINESTRING ((77.5785 13.04769, 77.57867 1..."
44531,762411542,5112,trunk,NaN,NH67,B,0,0,F,F,"MULTILINESTRING ((76.45075 15.24065, 76.45024 ..."
44550,762500475,5112,trunk,Bangalore-Mysore Road,NH275,F,60,0,F,F,"MULTILINESTRING ((77.51843 12.93633, 77.51825 ..."
44551,762500476,5112,trunk,Mysore Road,NH275,F,0,0,F,F,"MULTILINESTRING ((77.53309 12.94741, 77.53295 ..."
44552,762500477,5112,trunk,Mysore Road,NH275,F,0,0,F,F,"MULTILINESTRING ((77.54136 12.9526, 77.54117 1..."

In [9]:
filtered.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [10]:
roads_reprojected = filtered.to_crs('EPSG:32643')
roads_reprojected.crs

<Projected CRS: EPSG:32643>
Name: WGS 84 / UTM zone 43N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 72°E and 78°E, northern hemisphere between equator and 84°N, onshore and offshore. China. India. Kazakhstan. Kyrgyzstan. Maldives. Pakistan. Russian Federation. Tajikistan. Uzbekistan.
- bounds: (72.0, 0.0, 78.0, 84.0)
Coordinate Operation:
- name: UTM zone 43N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [12]:
roads_reprojected['length'] = roads_reprojected['geometry'].length

In [ ]:
total_length = roads_reprojected['length'].sum() #meter
print(f'Total length of national highways in the state is {total_length/1000} KM')

Total length of national highways in the state is 8616.166058402969 KM