In [3]:
import geopandas as gpd

In [ ]:
import os
data_folder_path = 'data'
filename = 'karnataka.gpkg'
path = os.path.join(data_folder_path, filename)

In [5]:
roads_gdf = gpd.read_file(path, layer='karnataka_major_roads')
roads_gdf

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry
0,4354953,5114,secondary,Mahatma Gandhi Road,NaN,F,30,0,F,F,"MULTILINESTRING ((77.59928 12.97672, 77.5995 1..."
1,8285861,5114,secondary,NaN,NaN,B,0,0,F,F,"MULTILINESTRING ((76.65944 12.31809, 76.65904 ..."
2,8285868,5113,primary,Bangalore Nilgiri Road,NaN,F,0,0,F,F,"MULTILINESTRING ((76.65906 12.31389, 76.65912 ..."
3,8285890,5115,tertiary,Sri Harsha Road,NaN,F,0,0,F,F,"MULTILINESTRING ((76.656 12.30895, 76.65646 12..."
4,8285892,5114,secondary,Ashoka Road,NaN,F,0,0,F,F,"MULTILINESTRING ((76.65615 12.30989, 76.656 12..."
...,...,...,...,...,...,...,...,...,...,...,...
44601,763293423,5114,secondary,Kamaraj Road,NaN,F,0,0,F,F,"MULTILINESTRING ((77.60806 12.97517, 77.60797 ..."
44602,763293424,5114,secondary,Mahatma Gandhi Road,NaN,F,30,0,F,F,"MULTILINESTRING ((77.60798 12.97519, 77.60806 ..."
44603,763295978,5114,secondary,18th Cross Road,NaN,B,0,0,F,F,"MULTILINESTRING ((77.57115 13.00849, 77.57156 ..."
44604,763405052,5113,primary,Varthur Road,NaN,F,0,0,F,F,"MULTILINESTRING ((77.7014 12.95693, 77.70164 1..."
44605,763405053,5113,primary,Field Marshal Cariappa Road,NaN,F,30,0,F,F,"MULTILINESTRING ((77.6104 12.9736, 77.61052 12..."

In [6]:
roads_gdf.geometry

0        MULTILINESTRING ((77.59928 12.97672, 77.5995 1...
1        MULTILINESTRING ((76.65944 12.31809, 76.65904 ...
2        MULTILINESTRING ((76.65906 12.31389, 76.65912 ...
3        MULTILINESTRING ((76.656 12.30895, 76.65646 12...
4        MULTILINESTRING ((76.65615 12.30989, 76.656 12...
                               ...
44601    MULTILINESTRING ((77.60806 12.97517, 77.60797 ...
44602    MULTILINESTRING ((77.60798 12.97519, 77.60806 ...
44603    MULTILINESTRING ((77.57115 13.00849, 77.57156 ...
44604    MULTILINESTRING ((77.7014 12.95693, 77.70164 1...
44605    MULTILINESTRING ((77.6104 12.9736, 77.61052 12...
Name: geometry, Length: 44606, dtype: geometry

In [7]:
filtered = roads_gdf[roads_gdf['ref'].str.match('^NH') == True]
filtered

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry
17,8684837,5112,trunk,Bengaluru - Mangaluru Road,NH373,F,0,0,F,F,"MULTILINESTRING ((76.10024 13.00326, 76.0995 1..."
26,9951034,5112,trunk,NaN,NH948,B,50,0,F,F,"MULTILINESTRING ((77.16472 12.24774, 77.16416 ..."
54,22838314,5112,trunk,Solapur-Mangalore Highway,NH169,B,0,0,F,F,"MULTILINESTRING ((74.86387 12.88387, 74.86418 ..."
55,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,"MULTILINESTRING ((74.78756 13.09142, 74.78744 ..."
56,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,"MULTILINESTRING ((74.78767 13.09723, 74.78767 ..."
...,...,...,...,...,...,...,...,...,...,...,...
44466,760685447,5112,trunk,Outer Ring Road,NH75,F,60,0,F,F,"MULTILINESTRING ((77.5785 13.04769, 77.57867 1..."
44531,762411542,5112,trunk,NaN,NH67,B,0,0,F,F,"MULTILINESTRING ((76.45075 15.24065, 76.45024 ..."
44550,762500475,5112,trunk,Bangalore-Mysore Road,NH275,F,60,0,F,F,"MULTILINESTRING ((77.51843 12.93633, 77.51825 ..."
44551,762500476,5112,trunk,Mysore Road,NH275,F,0,0,F,F,"MULTILINESTRING ((77.53309 12.94741, 77.53295 ..."
44552,762500477,5112,trunk,Mysore Road,NH275,F,0,0,F,F,"MULTILINESTRING ((77.54136 12.9526, 77.54117 1..."

In [9]:
filtered.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [10]:
roads_reprojected = filtered.to_crs('EPSG:32643')
roads_reprojected.crs

<Projected CRS: EPSG:32643>
Name: WGS 84 / UTM zone 43N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 72°E and 78°E, northern hemisphere between equator and 84°N, onshore and offshore. China. India. Kazakhstan. Kyrgyzstan. Maldives. Pakistan. Russian Federation. Tajikistan. Uzbekistan.
- bounds: (72.0, 0.0, 78.0, 84.0)
Coordinate Operation:
- name: UTM zone 43N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [12]:
roads_reprojected['length'] = roads_reprojected['geometry'].length

In [ ]:
total_length = roads_reprojected['length'].sum() #meter
print(f'Total length of national highways in the state is {total_length/1000} KM')

Total length of national highways in the state is 8616.166058402969 KM

In [16]:
districts_gdf = gpd.read_file(path, layer='karnataka_districts')
districts_gdf

,DISTRICT,ST_NM,ST_CEN_CD,DT_CEN_CD,censuscode,geometry
0,Bagalkot,Karnataka,29,2,556,"MULTIPOLYGON (((76.241 16.16531, 76.23538 16.1..."
1,Bangalore Rural,Karnataka,29,29,583,"MULTIPOLYGON (((77.38701 13.50002, 77.40099 13..."
2,Bangalore,Karnataka,29,18,572,"MULTIPOLYGON (((77.83549 12.86809, 77.83213 12..."
3,Belgaum,Karnataka,29,1,555,"MULTIPOLYGON (((75.02647 16.93264, 75.02827 16..."
4,Bellary,Karnataka,29,11,565,"MULTIPOLYGON (((77.15757 15.13706, 77.15887 15..."
5,Bidar,Karnataka,29,4,558,"MULTIPOLYGON (((77.34032 18.43689, 77.3451 18...."
6,Bijapur,Karnataka,29,3,557,"MULTIPOLYGON (((76.07344 17.33403, 76.0703 17...."
7,Chamrajnagar,Karnataka,29,24,578,"MULTIPOLYGON (((77.32282 12.30709, 77.32726 12..."
8,Chikkaballapura,Karnataka,29,28,582,"MULTIPOLYGON (((78.1996 13.56615, 78.19897 13...."
9,Chikmagalur,Karnataka,29,16,570,"MULTIPOLYGON (((76.35411 13.5777, 76.35611 13...."
10,Chitradurga,Karnataka,29,12,566,"MULTIPOLYGON (((76.76081 14.988, 76.76246 14.9..."
11,Dakshina Kannada,Karnataka,29,21,575,"MULTIPOLYGON (((75.20194 13.1814, 75.20992 13...."
12,Davanagere,Karnataka,29,13,567,"MULTIPOLYGON (((76.5083 14.56379, 76.50964 14...."
13,Dharwad,Karnataka,29,8,562,"MULTIPOLYGON (((75.41951 15.06168, 75.41887 15..."
14,Gadag,Karnataka,29,7,561,"MULTIPOLYGON (((75.84568 15.83773, 75.87617 15..."
15,Gulbarga,Karnataka,29,25,579,"MULTIPOLYGON (((76.6922 17.68175, 76.69516 17...."
16,Hassan,Karnataka,29,20,574,"MULTIPOLYGON (((76.63191 13.00563, 76.63216 13..."
17,Haveri,Karnataka,29,10,564,"MULTIPOLYGON (((75.41951 15.06168, 75.42 15.06..."
18,Kodagu,Karnataka,29,22,576,"MULTIPOLYGON (((76.02082 12.5665, 76.0146 12.5..."
19,Kolar,Karnataka,29,27,581,"MULTIPOLYGON (((77.92568 13.23829, 77.93388 13..."
20,Koppal,Karnataka,29,6,560,"MULTIPOLYGON (((76.28563 15.90133, 76.28563 15..."
21,Mandya,Karnataka,29,19,573,"MULTIPOLYGON (((76.68466 13.04283, 76.69453 13..."
22,Mysore,Karnataka,29,23,577,"MULTIPOLYGON (((77.11309 12.24232, 77.12558 12..."
23,Raichur,Karnataka,29,5,559,"MULTIPOLYGON (((77.28865 16.40704, 77.29859 16..."
24,Ramanagara,Karnataka,29,30,584,"MULTIPOLYGON (((77.20467 13.18377, 77.20798 13..."
25,Shimoga,Karnataka,29,14,568,"MULTIPOLYGON (((75.53624 14.27739, 75.5354 14...."
26,Tumkur,Karnataka,29,17,571,"MULTIPOLYGON (((76.97715 14.05873, 76.9553 14...."
27,Udupi,Karnataka,29,15,569,"MULTIPOLYGON (((75.14023 13.46326, 75.14106 13..."
28,Uttara Kannada,Karnataka,29,9,563,"MULTIPOLYGON (((74.32141 15.51751, 74.32975 15..."
29,Yadgir,Karnataka,29,26,580,"MULTIPOLYGON (((77.45652 16.88511, 77.46166 16..."

In [17]:
districts_reprojected = districts_gdf.to_crs('EPSG:32643')

A spatial join is performed using the sjoin() method. It takes 2 core arguments.

predicate: The spatial predicate to decide which objects to join. Options are intersects (geometries with at least one common point), within (first geometry completely contained in the second one) and contains (second geometry completely contained in the first one).

how: The type of join to perform. Options are left, right and inner.

In [18]:
joined = gpd.sjoin(roads_reprojected, districts_reprojected, how='left', predicate='intersects')
joined

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,geometry,length,index_right,DISTRICT,ST_NM,ST_CEN_CD,DT_CEN_CD,censuscode
17,8684837,5112,trunk,Bengaluru - Mangaluru Road,NH373,F,0,0,F,F,"MULTILINESTRING ((619317.005 1437753.696, 6192...",2352.939132,16.0,Hassan,Karnataka,29.0,20.0,574.0
26,9951034,5112,trunk,NaN,NH948,B,50,0,F,F,"MULTILINESTRING ((735483.761 1354892.067, 7354...",12876.925507,7.0,Chamrajnagar,Karnataka,29.0,24.0,578.0
54,22838314,5112,trunk,Solapur-Mangalore Highway,NH169,B,0,0,F,F,"MULTILINESTRING ((485231.162 1424297.721, 4852...",822.021433,11.0,Dakshina Kannada,Karnataka,29.0,21.0,575.0
55,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,"MULTILINESTRING ((476971.413 1447255.675, 4769...",648.925208,11.0,Dakshina Kannada,Karnataka,29.0,21.0,575.0
55,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,"MULTILINESTRING ((476971.413 1447255.675, 4769...",648.925208,27.0,Udupi,Karnataka,29.0,15.0,569.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44466,760685447,5112,trunk,Outer Ring Road,NH75,F,60,0,F,F,"MULTILINESTRING ((779647.578 1443830.443, 7796...",58.845924,2.0,Bangalore,Karnataka,29.0,18.0,572.0
44531,762411542,5112,trunk,NaN,NH67,B,0,0,F,F,"MULTILINESTRING ((655805.451 1685461.453, 6557...",1369.334392,4.0,Bellary,Karnataka,29.0,11.0,565.0
44550,762500475,5112,trunk,Bangalore-Mysore Road,NH275,F,60,0,F,F,"MULTILINESTRING ((773250.891 1431440.09, 77323...",487.316586,2.0,Bangalore,Karnataka,29.0,18.0,572.0
44551,762500476,5112,trunk,Mysore Road,NH275,F,0,0,F,F,"MULTILINESTRING ((774830.213 1432681.65, 77481...",15.561979,2.0,Bangalore,Karnataka,29.0,18.0,572.0
44552,762500477,5112,trunk,Mysore Road,NH275,F,0,0,F,F,"MULTILINESTRING ((775723.127 1433265.368, 7757...",338.656764,2.0,Bangalore,Karnataka,29.0,18.0,572.0

In this example, some road segments cross polygon boundaries. A spatial join will duplicate these segments for each polygon they intersect, resulting in an overestimation of the total length. A more accurate method is to use a Spatial Overlay, which splits segments at polygon boundaries. We can implement the overlay as below.

In [21]:
joined = roads_reprojected.overlay(districts_reprojected, how='intersection', keep_geom_type=True)
joined

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,length,DISTRICT,ST_NM,ST_CEN_CD,DT_CEN_CD,censuscode,geometry
0,8684837,5112,trunk,Bengaluru - Mangaluru Road,NH373,F,0,0,F,F,2352.939132,Hassan,Karnataka,29,20,574,"LINESTRING (619317.005 1437753.696, 619236.828..."
1,9951034,5112,trunk,NaN,NH948,B,50,0,F,F,12876.925507,Chamrajnagar,Karnataka,29,24,578,"LINESTRING (735483.761 1354892.067, 735422.762..."
2,22838314,5112,trunk,Solapur-Mangalore Highway,NH169,B,0,0,F,F,822.021433,Dakshina Kannada,Karnataka,29,21,575,"LINESTRING (485231.162 1424297.721, 485265.216..."
3,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,648.925208,Dakshina Kannada,Karnataka,29,21,575,"LINESTRING (476971.413 1447255.675, 476958.488..."
4,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,648.925208,Udupi,Karnataka,29,15,569,"LINESTRING (476983.371 1447897.309, 476983.371..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3394,760685447,5112,trunk,Outer Ring Road,NH75,F,60,0,F,F,58.845924,Bangalore,Karnataka,29,18,572,"LINESTRING (779647.578 1443830.443, 779666.108..."
3395,762411542,5112,trunk,NaN,NH67,B,0,0,F,F,1369.334392,Bellary,Karnataka,29,11,565,"LINESTRING (655805.451 1685461.453, 655750.304..."
3396,762500475,5112,trunk,Bangalore-Mysore Road,NH275,F,60,0,F,F,487.316586,Bangalore,Karnataka,29,18,572,"LINESTRING (773250.891 1431440.09, 773231.8 14..."
3397,762500476,5112,trunk,Mysore Road,NH275,F,0,0,F,F,15.561979,Bangalore,Karnataka,29,18,572,"LINESTRING (774830.213 1432681.65, 774815.419 ..."
3398,762500477,5112,trunk,Mysore Road,NH275,F,0,0,F,F,338.656764,Bangalore,Karnataka,29,18,572,"LINESTRING (775723.127 1433265.368, 775702.377..."

In [22]:
joined['length'] = joined.geometry.length
joined

,osm_id,code,fclass,name,ref,oneway,maxspeed,layer,bridge,tunnel,length,DISTRICT,ST_NM,ST_CEN_CD,DT_CEN_CD,censuscode,geometry
0,8684837,5112,trunk,Bengaluru - Mangaluru Road,NH373,F,0,0,F,F,2.352939e+03,Hassan,Karnataka,29,20,574,"LINESTRING (619317.005 1437753.696, 619236.828..."
1,9951034,5112,trunk,NaN,NH948,B,50,0,F,F,1.287693e+04,Chamrajnagar,Karnataka,29,24,578,"LINESTRING (735483.761 1354892.067, 735422.762..."
2,22838314,5112,trunk,Solapur-Mangalore Highway,NH169,B,0,0,F,F,8.220214e+02,Dakshina Kannada,Karnataka,29,21,575,"LINESTRING (485231.162 1424297.721, 485265.216..."
3,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,6.489252e+02,Dakshina Kannada,Karnataka,29,21,575,"LINESTRING (476971.413 1447255.675, 476958.488..."
4,22838318,5112,trunk,NaN,NH66,B,0,0,F,F,4.692852e-10,Udupi,Karnataka,29,15,569,"LINESTRING (476983.371 1447897.309, 476983.371..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3394,760685447,5112,trunk,Outer Ring Road,NH75,F,60,0,F,F,5.884592e+01,Bangalore,Karnataka,29,18,572,"LINESTRING (779647.578 1443830.443, 779666.108..."
3395,762411542,5112,trunk,NaN,NH67,B,0,0,F,F,1.369334e+03,Bellary,Karnataka,29,11,565,"LINESTRING (655805.451 1685461.453, 655750.304..."
3396,762500475,5112,trunk,Bangalore-Mysore Road,NH275,F,60,0,F,F,4.873166e+02,Bangalore,Karnataka,29,18,572,"LINESTRING (773250.891 1431440.09, 773231.8 14..."
3397,762500476,5112,trunk,Mysore Road,NH275,F,0,0,F,F,1.556198e+01,Bangalore,Karnataka,29,18,572,"LINESTRING (774830.213 1432681.65, 774815.419 ..."
3398,762500477,5112,trunk,Mysore Road,NH275,F,0,0,F,F,3.386568e+02,Bangalore,Karnataka,29,18,572,"LINESTRING (775723.127 1433265.368, 775702.377..."

In [20]:
results = joined.groupby('DISTRICT')['length'].sum()/1000
results

DISTRICT
Bagalkot            258.449475
Bangalore           314.170539
Bangalore Rural     319.965959
Belgaum             528.922541
Bellary             304.789522
Bidar               247.348300
Bijapur             424.197281
Chamrajnagar        217.737255
Chikkaballapura     211.957819
Chikmagalur         334.423573
Chitradurga         531.932443
Dakshina Kannada    316.339566
Davanagere          177.877407
Dharwad             314.978752
Gadag               111.548768
Gulbarga            294.551578
Hassan              436.231356
Haveri              306.582730
Kodagu               63.806864
Kolar               221.598406
Koppal              288.358711
Mandya              337.555904
Mysore              361.510005
Raichur             167.746669
Ramanagara          199.426362
Shimoga             479.140995
Tumkur              613.177564
Udupi               277.331577
Uttara Kannada      424.184040
Yadgir              144.858328
Name: length, dtype: float64